events {}

http {
    upstream backend {
        server host.docker.internal:5000;
        server host.docker.internal:5001;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_next_upstream error timeout http_502 http_503 http_504;
        }
    }
}